### ISSUE TITLE
Handling notebooks

### ISSUE THREAD

**Issue by DamienIrving** [DamienIrving/cmdline_provenance#6]
At the moment if you run `cmdprov.new_log()` from a jupyter notebook it will return the command that was run in the background to launch the notebook, which isn't particularly helpful. Instead, the log entry needs to list the name of the notebook.

@MitchellBlack had a go at rolling his own function to get the notebook name at https://github.com/MitchellBlack/cmdline_provenance/commit/d8f1fc967bcfb69bfd9a88fd9af981a4fdca50cc, or the [ipynbname](https://github.com/msm1089/ipynbname) library might also be an option.

**Comment by MitchellBlack** [comment]
@DamienIrving I have uploaded my most recent attempt at cmdline_provenance which includes jupyter notebooks, refined from my previous version. 
https://github.com/MitchellBlack/cmdline_provenance/commit/fac847a2488cbd3995ecbd10a8a29ddb927218e5

**Comment by DamienIrving** [comment]
Included in v1.0.0 release.
